# -*- mode: ruby -*-
# vi: set ft=ruby :

# Since the webserver needs the IP of the DB server the two have to be started 
# in the right order and with storing the IP of the latter on the way:
#
# $ rm db_ip.txt | vagrant up | python store_ip.py

Vagrant.configure("2") do |config|
    config.vm.box = 'digital_ocean'
    config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    config.ssh.private_key_path = './id_rsa'
    SSH_KEY_NAME = "Nico Laptop"
    DIGITAL_OCEAN_TOKEN = "key"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
    config.vm.define "webserver", primary: false do |server|
  
      server.vm.provider :digital_ocean do |provider|
        provider.ssh_key_name = SSH_KEY_NAME
        provider.token = DIGITAL_OCEAN_TOKEN
        provider.image = 'ubuntu-18-04-x64'
        provider.region = 'fra1'
        provider.size = 's-1vcpu-1gb'
        provider.privatenetworking = true
      end

      server.vm.hostname = "webserver"
      #config.vm.network :forwarded_port, guest: 7077, host: 7077
      #config.vm.network :forwarded_port, guest: 5077, host: 5077
      
      config.ssh.shell = %{bash -c 'BASH_ENV=/etc/profile exec bash'}
      
      config.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        export LANGUAGE=en_US.UTF-8
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        locale-gen en_US.UTF-8
        dpkg-reconfigure locales
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get install apt-transport-https -y
        sudo apt-get update -y
        sudo apt-get install dotnet-sdk-6.0 -y
      SHELL
    
    
      server.vm.provision "shell", inline: <<-SHELL
        echo "Installing Anaconda..."
        sudo wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O $HOME/Anaconda3-2019.07-Linux-x86_64.sh
    
        bash ~/Anaconda3-2019.07-Linux-x86_64.sh -b
        
        echo ". $HOME/.bashrc" >> $HOME/.bash_profile
        echo "export PATH=$HOME/anaconda3/bin:$PATH" >> $HOME/.bash_profile
        export PATH="$HOME/anaconda3/bin:$PATH"
        rm Anaconda3-2019.07-Linux-x86_64.sh
        source $HOME/.bash_profile

        cp -r /vagrant/* $HOME
        cd Minitwit
        nohup dotnet run > out.log &
        echo "================================================================="
        echo "=                            DONE                               ="
        echo "================================================================="
        echo "Navigate in your browser to:"
        THIS_IP=`hostname -I | cut -d" " -f1`
        echo "http://${THIS_IP}:7077"
      SHELL
    end

    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        sudo apt-get update
    SHELL
    end