datasources:
  - name: 'shittytwitter'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'http://prometheus:9090'
    is_default: true
    version: 1
    editable: true
  - name: "defaultdb"
    org_id: 1
    type: "postgres"
    typeName: "PostgreSQL"
    access: "proxy"
    url: "db-postgresql-fra1-40527-do-user-10842035-0.b.db.ondigitalocean.com:25060"
    password: ""
    user: "doadmin"
    database: "defaultdb"
    basicAuth: false
    isDefault: false
    jsonData: 
      postgresVersion: 1200
      sslmode: "require"
      tlsAuth: true
      tlsAuthWithCACert: true
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: false
    readOnly: false
    