name: Actionlint
    
on:
  pull_request:
    branches: [ master , dev]
    types: [opened, synchronize, reopened]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check all workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -verbose
        shell: bash