name: .NET

defaults:
  run:
    shell: bash
    working-directory: aspnet/
    
on:
  push:
    branches: [ 'feature/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : machine echo $HOME
      run : "echo $HOME"
    - name : machine ls $HOME
      working-directory : "."
      run : "ls -la $HOME"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
